# Generated by Django 5.1.5 on 2025-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "excel_processor",
            "0003_excelprocessorfileuploadregistryhubvaluedate_excel_proce_value_d_17c026_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="excelprocessorfileuploadregistrystaticsatellite",
            name="celery_task_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="excelprocessorfileuploadregistrystaticsatellite",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploaded", "Uploaded"),
                    ("in_progress", "In Progress"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
