# Generated by Django 5.2.9 on 2026-02-02 14:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_processor', '0004_excelprocessorfileuploadregistrystaticsatellite_celery_task_id_and_more'),
        ('file_upload', '0017_fileuploadregistrystaticsatellite_celery_task_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkExcelProcessorRegistryProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_processor.excelprocessorfileuploadregistryhub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileuploadfilehub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='excelprocessorfileuploadregistryhub',
            name='link_file_upload_registry_file_processed_file',
            field=models.ManyToManyField(related_name='link_file_processed_file_excel_processor_registry', through='excel_processor.LinkExcelProcessorRegistryProcessedFile', to='file_upload.fileuploadfilehub'),
        ),
    ]
