# Generated by Django 5.2.9 on 2026-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_processor", "0005_linkexcelprocessorregistryprocessedfile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelprocessorfileuploadregistrystaticsatellite",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("csv", "Csv"),
                    ("json", "Json"),
                    ("xml", "Xml"),
                    ("xlsx", "Xlsx"),
                    ("xls", "Xls"),
                    ("txt", "Txt"),
                    ("toml", "Toml"),
                    ("none", "None"),
                ],
                default="none",
                max_length=5,
            ),
        ),
    ]
