# Generated by Django 5.2.9 on 2026-03-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebookdatasatellite',
            old_name='data_line',
            new_name='data_row',
        ),
    ]
