# Generated by Django 5.2.9 on 2026-03-04 08:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_linknotebookfieldsnotebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkNotebookDataNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_date_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('state_date_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc))),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('hub_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.notebookdatahub')),
                ('hub_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.notebookhub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notebookdatahub',
            name='link_notebook_data_notebook',
            field=models.ManyToManyField(related_name='link_notebook_notebook_data', through='notebook.LinkNotebookDataNotebook', to='notebook.notebookhub'),
        ),
    ]
